project_id = "ryeviupygrrmoyxoycwl"

[functions.generate-blog]
verify_jwt = false

[functions.generate-email-funnel]
verify_jwt = false

[functions.ai-designer]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.lookup-orders]
verify_jwt = false

[functions.auto-blog]
verify_jwt = false

[functions.amazon-mcf]
verify_jwt = false


[auth]
site_url = "https://hwabelle.shop"
additional_redirect_urls = ["https://hwabelle.com/*", "https://www.hwabelle.com/*", "https://hwabelle.shop/*", "https://www.hwabelle.shop/*", "http://localhost:3000/*"]

[auth.email]
enable_confirmations = true

[auth.email.template.confirmation]
subject = "Confirm Your Signup"
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.recovery]
subject = "Reset Your Password"
content_path = "./supabase/templates/recovery.html"

[auth.email.template.magic_link]
subject = "Your Magic Link"
content_path = "./supabase/templates/magic_link.html"

[auth.email.template.email_change]
subject = "Confirm Email Change"
content_path = "./supabase/templates/email_change.html"

[auth.email.template.invite]
subject = "You have been invited"
content_path = "./supabase/templates/invite.html"

[functions.reset-test-user]
enabled = true
verify_jwt = true
import_map = "./functions/reset-test-user/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/reset-test-user/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/reset-test-user/*.html" ]

[functions.delete-mock-user]
enabled = true
verify_jwt = true
import_map = "./functions/delete-mock-user/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/delete-mock-user/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/delete-mock-user/*.html" ]
